### ISSUE TITLE
Multiple route attributes

### ISSUE THREAD

**Issue by TheTrigger** [FastEndpoints/Library#129]
Hello, I'm trying this library for the first time, I immediately ran into this limit `Duplicate 'HttpGet' attribute`
while the asp.net core controllers allow it

```csharp
[HttpGet("/api/session/me")]
[HttpGet("/api/session/")] // <--- Duplicate 'HttpGet' attribute
[AllowAnonymous]
public class SessionEndpoint : Endpoint<EmptyRequest, CurrentSessionResponse>
{
    public override async Task HandleAsync(EmptyRequest request, CancellationToken cancellationToken)
    {
        var response = new CurrentSessionResponse
        {
            ...
        };

        await SendAsync(response, cancellation: cancellationToken).ConfigureAwait(false);
    }
}
```

is this a feature that will be supported?

thanks

**Comment by dj-nitehawk** [comment]
it's currently not supported atm with attributes. 
but available via configure method as shown here: https://github.com/dj-nitehawk/FastEndpoints/blob/1c1ac25cd0f4e9e70c952f0f51cbb658271f6905/Web/%5BFeatures%5D/Customers/Create/Endpoint.cs#L39

will look into supporting it in the future.

**Comment by nefarius** [comment]
Not sure if it's as easy as I've envisioned but I started tinkering with this request [in a new branch](https://github.com/nefarius/FastEndpoints/tree/nefarius/feature/multiple-http-attributes).

**Comment by dj-nitehawk** [comment]
@nefarius 

> Not sure if it's as easy as I've envisioned

yeah that's why i've left this open for this long...

ultimately the `EndpointDefinition.Routes` and `EndpointDefinition.Verbs` is what determines what and how many routes are registered.

for example:
```cs
Routes("first","Second");
Verbs(HTTP.Get, HTTP.Post);
```
results in 2 x 2 = 4 routes being registered. 2 verbs per route.

i believe this gets tricky when you do multiple http attributes yes?

**Comment by nefarius** [comment]
> results in 2 x 2 = 4 routes being registered. 2 verbs per route.

So what you're saying is, the user can not do this anyway:
- `/api/submit` only allow `POST`
- `/api/status` only allow `GET`

If we do
```csharp
Routes("/api/submit","/api/status");
Verbs(HTTP.Get, HTTP.Post);
```
this leads to both `/api/submit` and `/api/status` being available for both `GET` and `POST`, am I right?

**Comment by dj-nitehawk** [comment]
correct. 
the way to achieve that would be a separate endpoint class,  which can be a derived class if the handler logic is exactly the same.

**Comment by nefarius** [comment]
Hm, so the [cheap trickery I pulled off here](https://github.com/FastEndpoints/Library/compare/main...nefarius:FastEndpoints:nefarius/feature/multiple-http-attributes#diff-78339c95d8c6aa0551667ff7213ae6992362070796894e7a6d53080bda1ee46f) might actually work then?

**Comment by dj-nitehawk** [comment]
if it works, then it works ;-)

**Comment by nefarius** [comment]
Onwards to testing then 🏃‍♂️

**Comment by dj-nitehawk** [comment]
@nefarius i decided to go a bit different route... pun intended ;-)

so for multiple routes, intead of duplicate attribute annotations, user can specify multiple routes like so:
```cs
[HttpGet("/api/session/me", "/api/session")]
```
this way there's less clutter and no confusion with the limitation of multiple verbs.

**Comment by nefarius** [comment]
Looks good and simple to understand!
