### ISSUE TITLE
Minimum .NET Core version is not mentioned anywhere in the home page

### ISSUE THREAD

**Issue by dcarapic** [FastEndpoints/Library#178]
Perhaps I'm blind but I can not see what is the minimum supported .NET Core version for this library. 
It would be nice if this was mentioned somewhere on the home page (https://fast-endpoints.com).

**Comment by dj-nitehawk** [comment]
.net core is not supported.
minimal api was introduced by microsoft at .net 6.0
so fastendpoints only supports .net 6.0 or newer...
thanks for the suggestion to add to home page.
