### ISSUE TITLE
Any way to render an HTML view?

### ISSUE THREAD

**Issue by andyolivares** [FastEndpoints/Library#180]
I have a project which is mostly composed by REST APIs but I need just one HTML view. Is it possible to do that with FastEndpoints somehow?

I guess I could instanciate Razor myself, render a view to a string and then spit it out, but I wonder if there is a better/supported way.

Thank you and great library BTW!

**Comment by dj-nitehawk** [comment]
yeah FE doesn't have a html rendering engine. that would be redundant since you're free to use razor pages in the same app as FE. or try the following:
- https://github.com/sebastienros/fluid
- https://r3c.github.io/cottle/

**Comment by andyolivares** [comment]
Thanks for the answer!

**Comment by MeikelLP** [comment]
There is also https://github.com/toddams/RazorLight if you wanna stick with `.cshtml` or just migrate (like I am)

**Comment by dj-nitehawk** [comment]
there's also the [RazorComponentResult](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/integration?view=aspnetcore-8.0#return-a-razorcomponentresult-from-an-mvc-controller-action) now. since it's an `IResult`, you can just do this:
```cs
await SendResultAsync(new RazorComponentResult<MyPage>(...));
```
or even this:
```cs
sealed class Endpoint : Endpoint<Request, RazorComponentResult<Response>>
{
    public override async Task<RazorComponentResult<MyPage>> ExecuteAsync(Request req, CancellationToken ct)
    {
        await Task.CompletedTask;
        return new(...);
    }
} 
```

**Comment by dj-nitehawk** [comment]
@mhflam 
you should be using `SendResultAsync()` and not `SendAsync()`
