### ISSUE TITLE
Swagger randomly generates nullable properties

### ISSUE THREAD

**Issue by MarcBroers** [FastEndpoints/Library#185]
So first of all, I would like to thank you guys for this beautiful framework. It made developing in .NET way more fun and productive!

I've just discovered one of the strangest behaviors in the Swagger generation.
There are 2 models; Reference and GeographicalArea. Both of them have non-nullable strings ([I've enabled Nullable Strictness]
![Untitled-3](https://user-images.githubusercontent.com/48513423/184019228-61080045-fd65-422e-b338-cf451b1451f5.png)
In the Swagger schema, the Reference model has a required Name but GeographicalArea doesn't, while both type definitions are the same. This happens randomly across all the string properties on my models.
![Untitled-2](https://user-images.githubusercontent.com/48513423/184019125-0c335589-e153-45a2-8028-e0afd622e835.png)
![Untitled](https://user-images.githubusercontent.com/48513423/184019132-0dbd0566-042f-4e93-bcb5-7aa34c6c645f.png)

**What I expected:** All non-nullable strings marked as required in the schema.

**Things that I've tried:**

- Cleaning the solution
- Restoring all packages
- Cleaning browser cache

**Sidenotes**
- I'm running the following FastEndpoint packages: FastEndpoints.Swagger, FastEndpoints.Security, FastEndpoints (4.3.1, I've tried 4.4.0 aswell)
- I have no FluentValidation Schemas on the Response models.

**Comment by dj-nitehawk** [comment]
i can't seem to reproduce this at all.
can you put the following in a new project and modify it so that the issue can be reproduced?
this behavior is highly unlikely because fastendpoints swagger processor doesn't even touch the schema if there are no validators written for the request dto.
also pls upgrade to the latest [beta version](https://www.nuget.org/packages/FastEndpoints/4.5.0-beta7) and see if there's any difference.
```cs
using FastEndpoints;
using Microsoft.AspNetCore.Builder;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(s => s.ConfigureDefaults());
app.Run();

public class Reference
{
    public string Name { get; set; }
}

public class GeographicalArea
{
    public string Name { get; set; }
}

public class RefEndpoint : Endpoint<Reference>
{
    public override void Configure()
    {
        Post("ref");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Reference r, CancellationToken c)
    {
        await SendOkAsync();
    }
}

public class GeoEndpoint : Endpoint<GeographicalArea>
{
    public override void Configure()
    {
        Post("ref");
        AllowAnonymous();
    }

    public override async Task HandleAsync(GeographicalArea r, CancellationToken c)
    {
        await SendOkAsync();
    }
}
```

**Comment by MarcBroers** [comment]
Very weird but upgrading to the beta package seems to solve the problem. By the way, even weirder: We only seem to be able to reproduce this error on MacOS, Windows handles everything correctly.

We'll be using the Beta for now, but if you ever require more investigation on this issue, please let me know.

**Comment by wjax** [comment]
Thanks for the report.

We will look into it. Are you using a fluent validator? If so, could you
please share it?

J
