### ISSUE TITLE
Option to throw FastEndpoints.ValidationFailureException without being catch.

### ISSUE THREAD

**Issue by emilio-feliciano-562** [FastEndpoints/Library#186]
It would be nice to see the option of not catching FastEndpoints.ValidationFailureException https://github.com/FastEndpoints/Library/blob/main/Src/Library/Endpoint/Endpoint.cs#L63 so the pipeline can catch it using a exception handler middleware.

Scenario: One of our new projects that utilizes FastEndpoint (which is awesome btw) but it also has a middleware that handles exception and produces the response for any type of exception being thrown. https://github.com/khellang/Middleware/tree/master/src/ProblemDetails

As a workaround we override the provided `OnValidationFailed`  when creating new endpoints:
`public override void OnValidationFailed() => throw new ValidationFailureDetailsException(ValidationFailures);` where `ValidationFailureDetailsException` is a custom exception that takes the  a `List<FluentValidation.Results.ValidationFailure> ValidationFailures` as argument.

So the end result is pretty much forwarding the exception.

We also had the idea of passing the list of validation failure into the `HttpContext.Items` dictionary so it could be accessed by the next middleware.

**Comment by dj-nitehawk** [comment]
try `v4.5.0-beta9`

you can now do the following:
https://github.com/FastEndpoints/Library/blob/18e14093fc1b674290cf7056141ce7b59326aa60/Web/%5BFeatures%5D/TestCases/DontCatchExceptions/Endpoint.cs#L5-L10

and also `FastEndpoints.ValidationFailureException` now has a `Failures` property which you can inspect for the details.

**Comment by emilio-feliciano-562** [comment]
Nice new feature for 4.5, thanks.
