### ISSUE TITLE
PermissionsClaimType 能否通过类似于EndpointDiscoveryOptions Or Action<Config>来设置而不是固定死

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#187]
Can PermissionsClaimType be set up instead of fixed dead by something like `EndpointDiscoveryOptions `Or `Action<Config>`

![image](https://user-images.githubusercontent.com/13956765/184472433-64fe9eac-6ed8-400d-a8b6-99efa51fd354.png)

我现在的业务是需要JWT认证, but not use FastEndpoints.Security.JWTBearer  , 但是我又需要 HasPermissionAttribute 来验证特定的Permission,所以 有没有办法通过配置 自定义我的  PermissionsClaimType . 比如 permissions -> Permission  来完成我自己的认证

**Comment by dj-nitehawk** [comment]
google translate didn't do a good job in translating your chinese. hope i understood correctly.

you can now do the following in `v4.5.0-beta10`

```cs
app.UseFastEndpoints(c => c.PermissionsClaimType = "MyPerms");
```

do note however if you're customizing the permissions claim type, you should not be using the `FastEndpoints.Security` package and you should be handling the security yourself.

**Comment by vipwan** [comment]
![492C2CD4](https://user-images.githubusercontent.com/13956765/184479259-41a1613e-e1db-42a1-aafc-2ef1301a5365.png)
 You adjusted the content to really what I wanted to say, forgive my poor English
