### ISSUE TITLE
Proposal: Response-only mapper

### ISSUE THREAD

**Issue by KennethHoff** [FastEndpoints/Library#188]
<h2>Our current options:</h2>

Currently, whenever an Endpoint does not have a request object, you either have to:
a) Create your own custom mapping logic - creating inconsistencies in your architecture, or
b) Create an Endpoint using Empty Request Objects (like the built-in `EmptyRequest` struct). This has it's own sets of problems, like for example having options like `ToEntity` which makes no sense in this context, or having a request parameter in the `HandleAsync` method which will never be used

![image](https://user-images.githubusercontent.com/17124533/184480562-c8c9230d-229e-4ab9-86e5-a49e45a0a8e8.png)
![image](https://user-images.githubusercontent.com/17124533/184480572-e487ac42-750d-434f-81d5-0e3e7a411890.png)
![image](https://user-images.githubusercontent.com/17124533/184480579-d37649be-ea57-4649-a119-802385ba28d1.png)

Was this an oversight and/or simply not been implemented yet, or is there a good reason this is currently not supported?

<h2>What I would like is this:</h2>

![image](https://user-images.githubusercontent.com/17124533/184480859-eb205a26-f0ce-4bca-8ce2-9c39f33231ba.png)
![image](https://user-images.githubusercontent.com/17124533/184481180-0d633552-4697-41fb-9998-2e2b86b03a46.png)
![image](https://user-images.githubusercontent.com/17124533/184480687-d27a5340-a7c8-41e6-a4d2-81ad2c038884.png)
![image](https://user-images.githubusercontent.com/17124533/184480708-746a1757-7e92-4eac-b65e-e46e0c0c7e9e.png)

**Comment by dj-nitehawk** [comment]
`v4.5.0-beta11` adds the following two new abstract classes
```cs
RequestMapper<TRequest,TEntity>
ResponseMapper<TResponse,TEntity>
```

**Comment by KennethHoff** [comment]
This feature only partially solves the problem - Albeit most of the way there (That might be my fault for being unclear however)

There is still no way to create an Endpoint without a request with a mapper. Although, most of the "gotchas" have been removed; You cannot call or override the `ToEntity`, `ToEntityAsync`, or `UpdateEntity` methods now.

It's a relatively minor thing though, but I'd like to not have to specify `EmptyRequest` in the Endpoint definition, and then have to add that (now unused) request object in the `HandleAsync` method)

![image](https://user-images.githubusercontent.com/17124533/184531802-924c46de-6b3d-4cec-895c-5e96c37d7e4e.png)

<h3>what I currently have to do, which <i>feels</i> wrong:</h3>

`EmptyRequest` in the following two images are only ever referenced in those two places

![Screenshot_20220814_115004](https://user-images.githubusercontent.com/17124533/184531639-3e0c1295-ae18-4c22-9769-e6c1c911da23.png)
![Screenshot_20220814_115014](https://user-images.githubusercontent.com/17124533/184531646-fe3a02e4-1813-4880-9b33-ae62064b6c33.png)

<h3>what I would prefer:</h3>

![Screenshot_20220814_115039](https://user-images.githubusercontent.com/17124533/184531652-d270e24d-4870-43ef-af1d-43e3727f0fe1.png)
![Screenshot_20220814_115043](https://user-images.githubusercontent.com/17124533/184531654-0e906e1a-c129-4e71-b9f6-9b11edbee837.png)

It was a good idea adding a Request-Only mapper while you're at it though

Sorry for being so greedy :p

(PS: You haven't uploaded beta10 or beta11 to NuGet, so I had to compile it and add the .dll manually)

**Comment by dj-nitehawk** [comment]
it's done with `v4.5.0-beta13`
nuget has a known issue with the version ordering after beta10.
but it's there: https://www.nuget.org/packages/FastEndpoints/4.5.0-beta13

**Comment by KennethHoff** [comment]
>nuget has a known issue with the version ordering after beta9.

Ah, they sort alphabetically :|

I think you forgot something: `EndpointWithoutRequest` only has the `Map` property. It doesn't have all the other Endpoint methods, like `HandleAsync` or `Configure` -- forgot to add the Endpoint baseclass perhaps? :smile:

**Comment by dj-nitehawk** [comment]
lol sorry... managing 6 different projects simultaneously...
fixed in `v4.5.0-beta14`
should be live in about 5mins...

**Comment by KennethHoff** [comment]
Additionally, `EndpointWithMapper` and `EndpointWithMapping` could be very confusing.

How about `EndpointWithoutResponse` to be consistent with the `EndpointWithoutRequest`?

**Comment by KennethHoff** [comment]
>lol sorry... managing 6 different projects simultaneously...

You're doing a tremendous job - it's a sunday for darn sake!

**Comment by dj-nitehawk** [comment]
> Additionally, `EndpointWithMapper` and `EndpointWithMapping` could be very confusing.
> 
> How about `EndpointWithoutResponse` to be consistent with the `EndpointWithoutRequest`?

will look in to that sometime soon...

**Comment by KennethHoff** [comment]
I've asked for two features so far - this(obviously :S ), and [default values for Swagger](https://discord.com/channels/933662816458645504/1003942423174598656/1003942426584551514) and both were implemented within a timespan that is unreasonable.

Thank you very much for your hard work! I sent $20 your way :coffee: o/

**Comment by dj-nitehawk** [comment]
received with much thanks 🙏
greatly appreciated...

these were not too difficult requests. hence the implementation speed 😉

and they do add good value to the library. so I'm happy to get them done as fast as I can.

keep em coming and gave a great day! 

btw join us on discord to keep an eye out on the latest developments. 

tc!

**Comment by KennethHoff** [comment]
>btw join us on discord to keep an eye out on the latest developments.

I am! :tada: 

BetweenNames#4911 ([Made this post, which I referenced in my last comment](https://discord.com/channels/933662816458645504/1003942423174598656/1003942426584551514) :P ))
