### ISSUE TITLE
move default request binder logic to a `RequestBinder<TRequest>` class

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#189]
Please take a look at the pseudocode in the screenshot  , I don't want to override all the bindings for properties , because most of them are correct . 

![image](https://user-images.githubusercontent.com/13956765/184481868-48ab070e-8a30-4d2c-8b9c-4f6f2a246519.png)

![image](https://user-images.githubusercontent.com/13956765/184484994-7e9b6f5c-8953-4052-b047-9817cf4ac53a.png)

![image](https://user-images.githubusercontent.com/13956765/184482530-45ec1d71-6797-43de-86eb-e575b8ea539c.png)

**Comment by dj-nitehawk** [comment]
implemented in `v4.5.0-beta12`
now you can inherit from `RequestBinder<TRequest>` class and override the `BindAsync()` method:
https://github.com/FastEndpoints/Library/blob/7d0491ec457e1e00492cce140b3e2a0a372f317c/Web/%5BFeatures%5D/TestCases/CustomRequestBinderTest/Models.cs#L19-L30

**Comment by vipwan** [comment]
The response was so prompt ! Thank you very much !!!
