### ISSUE TITLE
Outsourcing validators to separate class-lib is not possible

### ISSUE THREAD

**Issue by MichaelHochriegl** [FastEndpoints/Library#190]
I have the following project setup:
![Screenshot from 2022-08-14 15-12-59](https://user-images.githubusercontent.com/78933445/184540055-6c952952-0c07-4382-aa4b-d8ba34d0bc6c.png)

My requests, responses and validators are living outside of the API project that references `FastEndpoints` in a project called `Contract`. This is done to allow for easy integration of requests, responses and validators into the API and Blazor frontends.

Due to changes in #141 `AbstractValidator<T>` instances are no longer registered by `FastEndpoints`, so  this doesn't work any longer.
Installing `FastEndpoints` into the `Contract` class lib is not an option as this will break Blazor WASM with the following error:
```
Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(427, 5): [NETSDK1082] There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.
```

**Comment by MichaelHochriegl** [comment]
I know that @wjax will provide a proper solution for this, but for learning purposes I dabbled a little bit with the source code and got a solution working. My current solution can be found in [this branch](https://github.com/MichaelHochriegl/FastEndpoints/tree/feat/190_validation-registration-config).

For a quick glance here are my changes (I've added some comments to see my changes better):
`EndpointDiscoveryOptions.cs`
```csharp
    /// <summary>
    /// an optional list to allow the definition of what types should be handled as a validator.
    /// if no types are defined here only validators that inherit from <see cref="Validator{TRequest}"/> are registered.
    /// </summary>
    public Type[]? ValidationTypes { get; set; }
```

`EndpointData.cs`
```csharp
private static EndpointDefinition[] BuildEndpointDefinitions(IServiceCollection services, EndpointDiscoveryOptions? options,
        ConfigurationManager? config)
    {
        if (options?.DisableAutoDiscovery is true && options.Assemblies?.Any() is false)
            throw new InvalidOperationException("If 'DisableAutoDiscovery' is true, a collection of `Assemblies` must be provided!");

        Stopwatch.Start();

        //also update FastEndpoints.Generator if updating these
        IEnumerable<string> excludes = new[]
        {
            "Microsoft",
            "System",
            "FastEndpoints",
            "testhost",
            "netstandard",
            "Newtonsoft",
            "mscorlib",
            "NuGet",
            "NSwag",
            "FluentValidation",
            "YamlDotNet",
            "Accessibility",
            "NJsonSchema",
            "Namotion"
        };
        
        // added this here to get the configured validation types if any
        var validationTypes = Enumerable.Empty<Type>();
        if (options?.ValidationTypes?.Any() is true)
        {
            validationTypes = options.ValidationTypes;
        }

        var discoveredTypes = options?.SourceGeneratorDiscoveredTypes ?? Enumerable.Empty<Type>();

        if (!discoveredTypes.Any())
        {
            var assemblies = Enumerable.Empty<Assembly>();

            if (options?.Assemblies?.Any() is true)
            {
                assemblies = options.Assemblies;
                excludes = excludes.Except(options.Assemblies.Select(a => a.FullName?.Split('.')[0]!));
            }

            if (options?.DisableAutoDiscovery != true)
                assemblies = assemblies.Union(AppDomain.CurrentDomain.GetAssemblies());

            if (options?.AssemblyFilter is not null)
                assemblies = assemblies.Where(options.AssemblyFilter);

            // refactored this to be it's own list so I can add any configured validation types
            var typesToRegister = new List<Type>() {
                Types.IEndpoint,
                Types.IEndpointValidator,
                Types.IEventHandler,
                Types.ISummary
            };

            // add configured validation types
            typesToRegister.AddRange(validationTypes);

            discoveredTypes = assemblies
                .Where(a =>
                    !a.IsDynamic &&
                    !excludes.Any(n => a.FullName!.StartsWith(n)))
                .SelectMany(a => a.GetTypes())
                .Where(t =>
                    !t.IsAbstract &&
                    !t.IsInterface &&
                    !t.IsGenericType &&
                    t.GetInterfaces().Intersect(typesToRegister).Any());
        }

        //Endpoint<TRequest>
        //Validator<TRequest>

        var epList = new List<(Type tEndpoint, Type tRequest)>();

        //key: TRequest //val: TValidator
        var valDict = new Dictionary<Type, Type>();

        //key: TEndpoint //val: TSummary
        var summaryDict = new Dictionary<Type, Type>();

        foreach (var t in discoveredTypes)
        {
            foreach (var tInterface in t.GetInterfaces())
            {
                if (tInterface == Types.IEndpoint)
                {
                    var tRequest = t.GetGenericArgumentsOfType(Types.EndpointOf2)?[0] ?? Types.EmptyRequest;

                    services.AddTransient(t);
                    epList.Add((t, tRequest));
                    continue;
                }

                // changed this check here to see if the tInterface is part of any configured validation types
                if (validationTypes.Contains(tInterface))
                {
                    var tRequest = t.GetGenericArgumentsOfType(Types.ValidatorOf1)?[0]!;
                    if (!valDict.ContainsKey(tRequest))
                    {
                        valDict.Add(tRequest, t);
                    }
                    continue;
                }

                if (tInterface == Types.ISummary)
                {
                    var tEndpoint =
                        t.GetGenericArgumentsOfType(Types.SummaryOf1)?[0]! ??
                        t.GetGenericArgumentsOfType(Types.SummaryOf2)?[0]!;
                    summaryDict.Add(tEndpoint, t);
                    continue;
                }

                if (tInterface == Types.IEventHandler)
                {
                    ((IEventHandler?)Activator.CreateInstance(t))?.Subscribe();
                    continue;
                }
            }
        }
```

This will result in a setup like this in `Program.cs`:
```csharp
builder.Services.AddFastEndpoints(o =>
{
    o.SourceGeneratorDiscoveredTypes = DiscoveredTypes.All;
    o.ValidationTypes = new[] { typeof(IValidator) };
});
```

**Comment by dj-nitehawk** [comment]
this is what I had in mind: 
```cs
builder.Services.AddFastEndpoints(o =>
{
    o.SourceGeneratorDiscoveredTypes = DiscoveredTypes.All;
    o.IncludeAbstractValidators = true;
});
```

default value would be false. if user wants abstract validators discovered, just need to set a boolean. 

also need to make the source generator library consistent with this behavior.

**Comment by wjax** [comment]
I think there may be a cleaner solution.
The issue was a duplicated entry into a dictionary that holds the validators. If we change and filter to only add validators of relevant types (requests) we could safely scan everything without issue and extra config options...

**Comment by MichaelHochriegl** [comment]
Ah, just thought that with the solution that I went with a user could limit the scan to exactly those validators that need to be handled by FE. But honestly if there is a solution that doesn't require any setup I'm now than happy 😁

**Comment by wjax** [comment]
I have been thinking and I do like the idea from @MichaelHochriegl to include and specify what types the dev wants to be scanned / act as validators. That way devs have full control.

I would have preferred to specify the validator to use in the ```Configure``` method of every endpoint so it is absolutely clear what validator is used by the endpoint. However I know it breaks compatibility and @dj-nitehawk will not like it :)

If we go Michael's road, I would name the options field: ```CustomValidatorTypes``` so it is optional. If null (default), internal ```IEndpointValidator``` is used, otherwise the list is honored.
I would remove the duplication check and let an exception raise in case of duplicate validators for the same type so the dev is properly warned about the situation. In Michaels code, it would pass without being noticed.

**Comment by dj-nitehawk** [comment]
> I would have preferred to specify the validator to use in the `Configure` method of every endpoint

i absolutely don't mind if this can be made optional. i.e. if someone wants to be explicit about which validator they want with an endpoint they will have to first set a startup flag `c => c.Endpoints.SkipValidatorDiscovery = true` and then call a `Validator<TValidator>()` method inside `Configure()`. if they haven't disabled validator discovery, then calling `Validator<TValidator>()` should throw to inform user of the correct usage. what do you think?

btw, the startup config has been [restructured](https://github.com/FastEndpoints/Library/blob/55b9dd335bf97d2f1d8549bc069b8fdadfca1cb5/Src/Library/changelog.md#breaking-changes).

and yeah we can do the `CustomValidatorTypes` config too. if not null, then `SkipValidatorDiscovery` should be `false`, or an error is thrown.

thoughts?

**Comment by MichaelHochriegl** [comment]
Thanks that my thought-process and first implementation attempt isn't wasted. I really like the approach to provide both configurations (at the endpoint `Configure` and global type registration).

I would try again to look at it, but again I'm totally aware that my code will not necessarily land in the lib.

I really like the global type registration because it will allow me to create my own interface (e.g. `IFastEndpointValidator`) in my project and these will get autowired as request validators.

**Comment by wjax** [comment]
Go for it Michael. Your code had nothing bad.

We can help if needed but I encourage you to send a PR as you had some progress already in place

**Comment by MichaelHochriegl** [comment]
I'm currently implementing the changes from your comments and I'm slightly struggling with the `FastEndpoints.Generator` changes that I need to make.

Currently the `EndpointsDiscoveryGenerator` still uses the `FluentValidation.IValidator` and registered this. I tried to retrieve the `FastEndpoints.EndpointDiscoveryOptions` from the `GeneratorExecutionContext` but that's not referenced by the Generator.

So how do I need to change the Generator project to allow the configuration of the registered validator types?

**Comment by dj-nitehawk** [comment]
you can ignore the generator for now. I'll look in to it later. for now it can be a limitation of the generator package. i.e. it will discover all validators.

**Comment by MichaelHochriegl** [comment]
Basic functionality is there, but I struggle with where to throw the exception when the user has misconfigured something (e.g. tries to use `Validator<TValidator>` in `Configure()` when `.Endpoints.SkipValidatorDiscovery = false` or not set). Same goes for the exception when the `CustomValidatorTypes` are set but `SkipValidatorDiscovery = true`.

Any tips where to throw them? And the type of exception, I would have chosen `InvalidOperationException` but you might prefer something different.

**Comment by dj-nitehawk** [comment]
can you start a draft PR?
I'll have to see what you have done to comment.

**Comment by dj-nitehawk** [comment]
guys give `v5.0.0-beta7` a whirl...

so... by default only validators inheriting from `FastEndpoints.Validator<TRequest>` are auto discovered and registered.

if someone wants to include `FluentValidation.AbstractValidator<TRequest>` validators as well, all they gotta do is:
```cs
builder.Services.AddFastEndpoints(o => o.IncludeAbstractValidators = true);
```

an exception will be thrown during startup if more than one validator is found for a single request dto. in which case the user needs to be explicit about which exact validator must be used in the endpoint configuration like so:
```cs
    public override void Configure()
    {
        Get("test");
        Validator<MyValidator>();
    }
```

so... what do you think?
have i missed anything?
