### ISSUE TITLE
Proposal: External ReSharper Annotations

### ISSUE THREAD

**Issue by KennethHoff** [FastEndpoints/Library#191]
[ReSharper](https://www.jetbrains.com/resharper/) or [Rider](https://www.jetbrains.com/rider/) - two very commonly used utilities for programming in c# - looks through your code to determine whether or not something is used or not, and "complains" if it's not.
![image](https://user-images.githubusercontent.com/17124533/184545022-6518cd08-b47a-4f74-9f5b-76e99f0859cf.png).

And since Endpoints(And Validators) are never directly accessed in the code, this warning will always show up on all endpoints and validator classes

There are three ways of removing this warning:

1. Actually using it (which does not make sense in this context)
2. Adding the [[UsedImplicitly]](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#UsedImplicitlyAttribute) Attribute from [JetBrains.Annotations](https://www.nuget.org/packages/JetBrains.Annotations/) to the class directly\*, or to the base class using the `ImplicitUseTargetFlags.WithInheritors` parameter on the Attribute
![image](https://user-images.githubusercontent.com/17124533/184545102-3cf3b513-57c4-47c3-982a-6b788c86f105.png)
3. Using so-called [External Annotations](https://www.jetbrains.com/help/resharper/Code_Analysis__External_Annotations.html). Jetbrains has some built-in ones, which they share on [GitHub](https://github.com/JetBrains/ExternalAnnotations)

As these Attributes do not get compiled when you build - as they're entirely there to help the developer - I do not believe simply adding these to the base classes does anything (Although, I might be wrong). Because of this, I believe you, as a library author, realistically only have one way of adding them, and that's option 3 - External Annotations.

Now, I don't know how to distribute these External Annotations - if you have to make a separate `FastEndpoints.ExternalAnnotations` NuGet package, or if you could add them to the base `FastEndpoints` package, or what have you. You could also maybe send a Pull Request to JetBrains' own list of External Annotations and ask them to add it to their list. However you do it is up to you, really.

I have an ExternalAnnotations file I made yesterday (This does not include the new features added in 4.5.0, so you'd have to add those yourself, or I could help if this is something you want to pursue).

Here's the 4.4.0 file (This makes `Access` implicit for all inheritors of the various Endpoints/Validators(That's what the `1` and `4` means respectively)). I never considered before writing this that maybe I could add it to the `BaseEndpoint` directly, removing a lot of boilerplate. I'll test this and update the post 

```xml
<?xml version="1.0" encoding="utf-8"?>
<assembly name="FastEndpoints">

	<!-- <Endpoints> -->
	<member name="T:FastEndpoints.Endpoint`3">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<member name="T:FastEndpoints.Endpoint`2">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<member name="T:FastEndpoints.EndpointWithoutRequest">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<member name="T:FastEndpoints.EndpointWithoutRequest`1">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<member name="T:FastEndpoints.EndpointWithMapping`3">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<!-- </End...points> -->

	<!-- <Validators> -->
	<member name="T:FastEndpoints.Validator`1">
		<attribute
			ctor="M:JetBrains.Annotations.UsedImplicitlyAttribute.#ctor(JetBrains.Annotations.ImplicitUseKindFlags,JetBrains.Annotations.ImplicitUseTargetFlags)">
			<argument>1</argument>
			<argument>4</argument>
		</attribute>
	</member>
	<!-- <Validators/>-->
</assembly>

```

\* This is what I've been doing so far. For reference, these attributes can also be applied to fields, properties (including specifically on `get`, `set`, `init`), methods, and so on - practically everywhere you can add Attributes

**Comment by KennethHoff** [comment]
I've looked into whether I can add them directly to `IEndpoint`/`BaseEndpoint` and while it does look like I can, it's not as clear to the developer what is happening.

When I add them to each endpoint base class manually (like I did above), you get this nice visual when hovering over the base class:
![image](https://user-images.githubusercontent.com/17124533/184546230-ae784d0b-9a7b-419a-b948-b1bb6791846b.png)

However, if you add it to `IEndpoint` or `BaseEndpoint` you do not, as the Attribute is technically not applied to the class you're hovering over:
![image](https://user-images.githubusercontent.com/17124533/184546307-115c6404-24e9-4e38-8225-d0d8cfa06784.png)

I guess you could add it to all of them - both `IEndpoint` to ensure all user-made Endpoint derivates also get it, and the library-made ones to give good feedback.

**Comment by KennethHoff** [comment]
Upon further reading, it does look like you could actually add the Attributes to the Source code and have the Metadata be preserved inside the NuGet package:

https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html
(First paragraph)

**Comment by dj-nitehawk** [comment]
well, adding a reference to a jetbrains package in the base library is definitely not an option. 

if you're willing to make the external annotations, what I can do is create a new repo for `FastEndpoints.JetbrainsAnnotations` and make you a collaborator on that repo so you can have direct commit/push access. would that work? so jetbrains users would only have to install that package right?

I've applied for an open source jetbrains license. might be able to look in to this more if/when I get it. 

let me know your thoughts.

**Comment by dj-nitehawk** [comment]
or if simply embedding the xml files in the base library is gonna work, we can do that too. a kilobyte or two won't be an issue I think. either way gonna need you to supply the xml files 😜

**Comment by KennethHoff** [comment]
According to JetBrains' website, all you have to do is the following:

> If you are going to publish some binaries (for example, via NuGet), place the annotations [Assembly.Name].ExternalAnnotations.xml file in the same folder where the annotated [Assembly.Name].dll file is located.

If you could copy-paste what I wrote above into such a file and make a beta-version on NuGet. If that works, I can make a Pull Request with one that works for all the Endpoints - including the newly added ones.

I cannot give any guarantee on maintaining such a file, but I can at least make one that's designed for 4.5.0 :)

**Comment by dj-nitehawk** [comment]
yep sounds like a plan. will push a new beta out first thing tomorrow morning. gonna doze off for the day now. ciao!

**Comment by dj-nitehawk** [comment]
`v4.5.0-beta15` pushed to nuget with above xml.
if that works, pls send in a PR.
i've placed the file [here](https://github.com/FastEndpoints/Library/tree/main/Src/Library/Jetbrains)
assembly name is transformed via msbuild:
https://github.com/FastEndpoints/Library/blob/65a3df12951f26bb6080f0b22d7672f4e1317edd/Src/Library/FastEndpoints.csproj#L22-L25

**Comment by KennethHoff** [comment]
It doesn't look like it was added to the correct location. These are the two only files in the `lib/net6.0` folder
![bilde](https://user-images.githubusercontent.com/17124533/184586061-f0e4a599-bac1-44a9-9102-cc7f563c5b17.png)

It seems to work if I manually add the file, like this:

![bilde](https://user-images.githubusercontent.com/17124533/184586116-ac296984-f18c-4d79-8a9a-a4b11cd4fb5e.png).

I'll send a PR now with the updated values anyhow

**Comment by dj-nitehawk** [comment]
check the nupkg here: https://www.nuget.org/packages/FastEndpoints/5.0.0-beta2
xml file is now included next to the dll

**Comment by KennethHoff** [comment]
This seems to work! 🕺

**Comment by dj-nitehawk** [comment]
beautiful... i'll close the issue for now. feel free to reopen if needed.
