### ISSUE TITLE
Is it possible to provide a support  (eg  SwaggerGenOptions) for ignoring document generation  outside of FastEndpoints in things like such as WebApi or MinimalApi

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#193]
Because I'm in hybrid development mode right now, part of the code is developed using WebApi & MinimalApi , but I want to block them in  Swagger Doc 

Or other implementations I can do ?

**Comment by vipwan** [comment]
The `[ApiExplorerSettings(IgnoreApi = true)]` attribute to implement it one by one, but that's not the result I want

**Comment by dj-nitehawk** [comment]
minimal api already has this support.
```cs
app.MapGet("/hidden-endpoint", () => "ok").ExcludeFromDescription();
```

**Comment by vipwan** [comment]
> minimal api already has this support.
> 
> ```cs
> app.MapGet("/hidden-endpoint", () => "ok").ExcludeFromDescription();
> ```

I know that both minimalapi and webapi can be set up one by one. I mean, is there a way to set it globally once to take effect
I'm currently developing on someone else's dll, so I can't change the base code

**Comment by dj-nitehawk** [comment]
our swagger operation processor only operates on fastendpoint endpoints.
https://github.com/FastEndpoints/Library/blob/c850f328196b72ebb8741612939e377b15b30c33/Src/Swagger/OperationProcessor.cs#L39-L46

**Comment by vipwan** [comment]
#246

**Comment by vipwan** [comment]
Probably other people have such a need, so I submitted a PR @dj-nitehawk
