### ISSUE TITLE
Static TryParse method for structures takes non-nullable out parameter

### ISSUE THREAD

**Issue by Damianu** [FastEndpoints/Library#194]
Custom TryParse method as described https://fast-endpoints.com/docs/model-binding#supported-dto-property-types works fine on classes but doesn't get called on structs making it harder to use strongly typed ids.

Edit: After a bit of testing and checking the implementation I realised it works, just takes non-nullable output which should be mentioned in the documentation(?).

**Comment by dj-nitehawk** [comment]
will update the docs about that. thanks!
