### ISSUE TITLE
Proposal: Support for streaming responses

### ISSUE THREAD

**Issue by KennethHoff** [FastEndpoints/Library#198]
I just finished watching @Elfocrash (Nick Chapsas)'s [latest video on MediatR](https://www.youtube.com/watch?v=2TT3suofNlo), and in that video he talked about how MediatR has added support for streaming responses - basically an Endpoint "type" that continuously sends a response to the requester.

_This is not a high priority request_. I currently have no use case for this feature. I can however see myself wanting to use it at some point in the future for _something_, and I figure the likelihood of it being implemented is higher if someone requests it.

**Comment by MichaelHochriegl** [comment]
FE already supports this, you can take a look at https://fast-endpoints.com/docs/server-sent-events

**Comment by dj-nitehawk** [comment]
haven't seen the video yet. 
like @MichaelHochriegl said, we've had SSE support for a while and you can send any IAsyncEnumerable which continuously pushes down results.

here's an example: 
https://github.com/dj-nitehawk/Hybrid-Inverter-Monitor/blob/dd10a048991a35c301a8eb6fb92054ffc487fe1e/src/Server/Endpoints/GetStatus/Endpoint.cs#L21

**Comment by KennethHoff** [comment]
Oh, wow. I guess it's already done 🤣

**Comment by JohnGalt1717** [comment]
There's another use case here which is literally returning an IAsyncEnumerable just like you can with minimalapis that do not use server sent events.

Instead this will use ndjson and dump the results of an IAsyncEnumerable which doesn't appear to be supported right now but is in high demand because of ChatGPT's API.

**Comment by dj-nitehawk** [comment]
@JohnGalt1717 here's how you can do that:
```cs
sealed class StreamEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("stream");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        //simply provide any IAsyncEnumerable<T> as argument
        await SendAsync(GetDataStream(ct));
    }

    static async IAsyncEnumerable<object> GetDataStream([EnumeratorCancellation] CancellationToken ct)
    {
        while (!ct.IsCancellationRequested)
        {
            await Task.Delay(1000);

            yield return new { guid = Guid.NewGuid() };
        }
    }
}
```
clinet side:
```cs
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Streaming Response Viewer</title>
<script>
    async function streamResponse(url) {
        const response = await fetch(url);
        const reader = response.body.getReader();
        while (true) {
            const { done, value } = await reader.read();
            if (done) {
                break;
            }
            document.getElementById('responseContent').innerText += new TextDecoder().decode(value);
        }
    }

    window.onload = function() {
        streamResponse('http://localhost:5001/stream');
    };
</script>
</head>
<body>
    <pre id="responseContent"></pre>
</body>
</html>

```

**Comment by JohnGalt1717** [comment]
Suggestion to add this as an example in the documentation.  Better would be to create a StreamingEndpoint that wrapped this and made it explicit.

**Comment by KateyBee** [comment]
@JohnGalt1717 Added to the CookBook under the `Serialization` section.
As for adding another endpoint base class variation, I don't think we'll be doing that, as there's already a lot of endpoint variations to maintain and it's not adding anything significant, since the only thing you need to do differently with a regular endpoint base, is to just not specify the `TResponse` generic argument.

**Comment by nhwilly** [comment]
This is great. Thank you.
