### ISSUE TITLE
How to show parameter field on swagger on a GET endpoint with no request body?

### ISSUE THREAD

**Issue by bentoaldohax** [FastEndpoints/Library#199]
I cannot find on the docs a way to show on Swagger the query param field to add a custom value. Am I not seeing something or is a missing feature? Would be awesome to pass via query params a page number to get a few results from the database.

**Comment by bentoaldohax** [comment]
I have read that but I am unable to generate something like this on Swagger.

![image](https://user-images.githubusercontent.com/104450705/185625514-9a6f0322-e21b-45af-a008-bd8078b47613.png)

**Comment by bentoaldohax** [comment]
My bad, I was using the default swagger and I did not installed FastEndpoints.Swagger package Now that I have done that it works. Sorry for the inconvenience. Closing this question.

**Comment by dj-nitehawk** [comment]
you can do it like this:
```cs
public class Params
{
    [DefaultValue("param val 1")]
    public string Param1 { get; set; }

    [DefaultValue("param val 2")]
    public string Param2 { get; set; }
}

public class Request
{
    [QueryParam]
    public Params Params { get; set; }
}

public class GetUsersEndpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("users");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        var param1 = Query<string>("Param1");
        var param2 = Query<string>("Param2");
        await SendOkAsync($"{param1} - {param2}");
    }
}
```
as you can see the limitation here is that there's no built in support to auto bind the querystring `?param1=val1&param2=val2` to to a `Params` object. it is also not supported in minimal apis.

**Comment by dj-nitehawk** [comment]
in the latest beta version `v5.0.0-beta6` you can use a custom request binder to get the the job done like so:
```cs
public class MyBinder : IRequestBinder<Request>
{
    public ValueTask<Request> BindAsync(BinderContext context, CancellationToken cancellation)
    {
        return ValueTask.FromResult(new Request()
        {
            Params = new()
            {
                Param1 = context.HttpContext.Request.Query["Param1"],
                Param2 = context.HttpContext.Request.Query["Param2"]
            }
        });
    }
}

public class GetUsersEndpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("users");
        AllowAnonymous();
        RequestBinder(new MyBinder());
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendOkAsync(r.Params);
    }
}
```

**Comment by bentoaldohax** [comment]
Cool, I'll try that. Thanks.

**Comment by kevinvenclovas** [comment]
2 years later, is there a other smart solution to handle this kind of 'problem'?

**Comment by dj-nitehawk** [comment]
@kevinvenclovas pls open a new issue describing your exact problem. cheers!

**Comment by kevinvenclovas** [comment]
@dj-nitehawk I want to add a QueryParam to my swagger without define a extra request object like this one:

```
 public class Request
 {
     [QueryParam]
     public string? Status { get; set; }
}
```

i tried to add this in my summary without the request object but swagger did not show this information:

s.Params["status"] = "XXXX";
