### ISSUE TITLE
Multiple Files in Swagger

### ISSUE THREAD

**Issue by bentoaldohax** [FastEndpoints/Library#200]
I have a request that has as a param an IFormFileCollection and Swagger won't allow me to upload multiple files, only lets me add multiple strings.

**Comment by dj-nitehawk** [comment]
this is not supported by the swagger spec: https://swagger.io/docs/specification/2-0/file-upload

see under heading: multiple uploads

> However, uploading an arbitrary number of files (an array of files) is not supported. There is an open feature request at https://github.com/OAI/OpenAPI-Specification/issues/254. For now, you can use a binary string array as a workaround for uploading an arbitrary number of files:

**Comment by bentoaldohax** [comment]
That's OpenApi 2.0 documentation. Open Api 3 allows multiple files according to this doc:

[](https://swagger.io/docs/specification/describing-request-body/file-upload/)

Under heading: Multiple File Upload

**Comment by dj-nitehawk** [comment]
looks like it's not supported by nswag yet. here's a minimal repro:
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApiDocument(s =>
{
    s.Title = "Minimal API";
    s.Version = "v1";
});

var app = builder.Build();
app.UseOpenApi();
app.UseSwaggerUi3();

app.MapPost("/file-collection", (IFormFileCollection files) => //not supported by nswag
{
    var xxx = files;
});

app.MapPost("/file-list", (List<IFormFile> files) => //not supported by nswag
{
    var xxx = files;
});

app.MapPost("/file", (IFormFile file) => //supported by nswag
{
    var xxx = file;
});

app.Run();
```
you might wanna open an issue with nswag. once they support it, we can implement it for fastendpoints. might even start working automatically.

**Comment by IeuanWalker** [comment]
https://github.com/RicoSuter/NSwag/issues/4118
