### ISSUE TITLE
Disallow bindings from other sources on optional claim binding.

### ISSUE THREAD

**Issue by szekelymatyas** [FastEndpoints/Library#202]
So i want to bind the role from claim like this:
```
    [FromClaim(claimType: ClaimTypes.Role, false)]
    public string? Role { get; set; }
``` 
My goal is to do something role related if you have one. In the swagger document i got this:
![image](https://user-images.githubusercontent.com/30692105/186357450-4f8c5b43-06c3-4576-95aa-93a66deb78f8.png)
I dont want to bind the role from quary or other source, but i want it to be optional (some users dont have any role), thus the request returns a 400.
I found this on the documantation:
![image](https://user-images.githubusercontent.com/30692105/186359014-2a156851-c0a8-423e-bc18-1fa5d5f6bff9.png)
Is there a way to disable higher priority binding soruces for this property? Link: https://fast-endpoints.com/docs/model-binding#from-user-claims

**Comment by dj-nitehawk** [comment]
this looks like a unique requirement which can be achieved with a custom request binder like this:
```cs
public class MyRequest
{
    [JsonIgnore, Newtonsoft.Json.JsonIgnore]
    public string? Role { get; set; }

    public string Id { get; set; }
}

public class MyRequestBinder : RequestBinder<MyRequest>
{
    public override async ValueTask<MyRequest> BindAsync(BinderContext ctx, CancellationToken ct)
    {
        var req = await base.BindAsync(ctx, ct);
        req.Role = ctx.HttpContext.User.ClaimValue(ClaimTypes.Role);
        return req;
    }
}

public class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("test");
        RequestBinder(new MyRequestBinder());
    }

    public override async Task HandleAsync(MyRequest r, CancellationToken c)
    {
        await SendAsync($"User Role: {r.Role}");
    }
}
```

**Comment by dj-nitehawk** [comment]
or just read the user role in the handler method without putting a property on your request dto for the role:
```cs
public override async Task HandleAsync(MyRequest r, CancellationToken c)
{
    var userRole = User.ClaimValue(ClaimTypes.Role);

    if (userRole is null)
    {
        ThrowError("User doesn't have a role claim!");
    }
    else
    {
        await SendAsync($"user role is: {userRole}");
    }
}
```

**Comment by szekelymatyas** [comment]
> this looks like a unique requirement which can be achieved with a custom request binder like this:
> 
> ```cs
> public class MyRequest
> {
>     [JsonIgnore]
>     public string? Role { get; set; }
> 
>     public string Id { get; set; }
> }
> 
> public class MyRequestBinder : RequestBinder<MyRequest>
> {
>     public override async ValueTask<MyRequest> BindAsync(BinderContext ctx, CancellationToken ct)
>     {
>         var req = await base.BindAsync(ctx, ct);
>         req.Role = ctx.HttpContext.User.ClaimValue(ClaimTypes.Role);
>         return req;
>     }
> }
> 
> public class MyEndpoint : Endpoint<MyRequest>
> {
>     public override void Configure()
>     {
>         Post("test");
>         RequestBinder(new MyRequestBinder());
>     }
> 
>     public override async Task HandleAsync(MyRequest r, CancellationToken c)
>     {
>         await SendAsync($"User Role: {r.Role}");
>     }
> }
> ```

Probably going to use something like this. Is there a way to implement my own attribute globaly?

**Comment by dj-nitehawk** [comment]
with `v5.1.0-beta1` you can now do the following:
```cs
public interface IHasRole
{
    string? Role { get; set; }
}

public class Request : IHasRole
{
    public string? Role { get; set; }
}

app.UseFastEndpoints(c => c.Binding.Modifier = (req, tReq, ctx, ct) =>
{
    if (req is IHasRole r)
    {
        r.Role = ctx.HttpContext.User.ClaimValue(ClaimTypes.Role) ?? "Guest";
    }
});
```

**Comment by szekelymatyas** [comment]
> with `v5.1.0-beta1` you can now do the following:
> 
> ```cs
> public interface IHasRole
> {
>     string? Role { get; set; }
> }
> 
> public class Request : IHasRole
> {
>     public string? Role { get; set; }
> }
> 
> app.UseFastEndpoints(c => c.Binding.Modifier = (req, tReq, ctx, ct) =>
> {
>     if (req is IHasRole r)
>     {
>         r.Role = ctx.HttpContext.User.ClaimValue(ClaimTypes.Role) ?? "Guest";
>     }
> });
> ```

I did almost the same thing with RequestBinder. I already started seaching a config to add request binder globally. Binding modifier is exactly what im looking for. Ty :)

**Comment by szekelymatyas** [comment]
Have one more question. Tried JsonIgnore and HideFromDocs on the Role property, but Swagger still shows it as query parameter. How to ignore it properly?  Haven t found any other Attribute yet.

**Comment by dj-nitehawk** [comment]
since swagger is a different universe, you're gonna need a custom operation processor like this:
```cs
public class MyOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext ctx)
    {
        var apiDescription = ((AspNetCoreOperationProcessorContext)ctx).ApiDescription;
        var reqDtoType = apiDescription.ParameterDescriptions.FirstOrDefault()?.Type;
        var opParams = ctx.OperationDescription.Operation.Parameters;

        if (reqDtoType?.GetInterfaces().Contains(typeof(IHasRole)) is true)
        {
            foreach (var param in opParams.ToArray())
            {
                if (param.Name == nameof(IHasRole.Role))
                    opParams.Remove(param);
            }
        }
        return true;
    }
}
```
register it at startup like this:
```cs
builder.Services.AddSwaggerDoc(s => s.OperationProcessors.Add(new MyOperationProcessor()));
```
