### ISSUE TITLE
RoutePrefixOverride not working inside UseFastEndpoints configuration

### ISSUE THREAD

**Issue by vebbo2** [FastEndpoints/Library#207]
Hi, I'm not sure, if it is a bug or I'm using this incorrectly. My use case is to update endpoints globally with a route prefix, depending on a module. Code below is a simplified version

Given the endpoint configuration:
```
public override void Configure()
{
    Get("/test");
    RoutePrefixOverride("module_api");
    AllowAnonymous();
}
```
I get correct endpoint route `/module_api/test`

But this does not work:
```
public override void Configure()
{
    Get("/test");
    AllowAnonymous();
}

app.UseFastEndpoints(c =>
{
	c.Endpoints.RoutePrefix = "api";

	c.Endpoints.Configurator = (endpoint) =>
	{
		endpoint.RoutePrefixOverride("module_api");
	};
});
```
and I get route `/api/test`

**Comment by dj-nitehawk** [comment]
should be sorted in `v5.1.0-beta3`.
will be on nuget in a few minutes...
thanks for reporting...

**Comment by dj-nitehawk** [comment]
do note that however setting route prefix override at a global level will make the endpoint level call ineffective and will be ignored.

**Comment by vebbo2** [comment]
It's working now, thanks for quick response
