### ISSUE TITLE
Summaries, Descriptions and Params are missing in 5.0

### ISSUE THREAD

**Issue by krjaction50** [FastEndpoints/Library#210]
Another behavior change in 5.0.  This code used to properly show this descriptions, summaries and param descriptions in Swagger.  They are now missing on all my endpoints.

        public override void Configure()
        {
            Get("/chartofaccounts/{enterpriseId}/entity/{entityId}");
            base.Configure();
            if (Helper.Isapigee())
                AllowAnonymous();
            Summary(s =>
            {
                s.Summary = "Returns Chart of Account Information";
                s.Description = "Returns Chart of Accounts for the Enterprise ID and Entity ID passed.";
                s.Params["enterpriseId"] = "The Enterprise ID for the request.";
                s.Params["entityId"] = "The Entity ID to the request.";
            });
        }

This code is in my startup in case it's possibly related.

        c.Endpoints.Configurator = ep =>
        {
            if (ep.Routes[0].StartsWith("/log") is false)
            {
                ep.Description(b => b
                .Produces<ErrorResponse>(400, "application/problem+json")
                .Produces<ErrorResponse>(401, "application/problem+json")
                .Produces<ErrorResponse>(403, "application/problem+json")
                .Produces<ErrorResponse>(404, "application/problem+json")
                .Produces<ErrorResponse>(500, "application/problem+json"));

                ep.Summary(s =>
                {
                    s[400] = PlatformRESTAPI.API.Helper.Error400Description;
                    s[401] = PlatformRESTAPI.API.Helper.Error401Description;
                    s[403] = PlatformRESTAPI.API.Helper.Error403Description;
                    s[404] = PlatformRESTAPI.API.Helper.Error404Description;
                    s[500] = PlatformRESTAPI.API.Helper.Error500Description;
                });
            }
        };

**Comment by dj-nitehawk** [comment]
pls try the latest beta `v5.1.0-beta7`
if problem persists, pls modify the following code to reproduce the problem.
i just tried the following with the beta and seems to be working fine.
possibly related to #207

```cs
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints(c => c.Endpoints.Configurator = ep =>
{
    if (ep.Routes?[0].StartsWith("/log") is false)
    {
        ep.Description(b => b
        .Produces<ErrorResponse>(400, "application/problem+json")
        .Produces<ErrorResponse>(401, "application/problem+json")
        .Produces<ErrorResponse>(403, "application/problem+json")
        .Produces<ErrorResponse>(404, "application/problem+json")
        .Produces<ErrorResponse>(500, "application/problem+json"));

        ep.Summary(s =>
        {
            s[400] = "PlatformRESTAPI.API.Helper.Error400Description";
            s[401] = "PlatformRESTAPI.API.Helper.Error401Description";
            s[403] = "PlatformRESTAPI.API.Helper.Error403Description";
            s[404] = "PlatformRESTAPI.API.Helper.Error404Description";
            s[500] = "PlatformRESTAPI.API.Helper.Error500Description";
        });
    }
});
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/chartofaccounts/{enterpriseId}/entity/{entityId}");
        AllowAnonymous();
        Summary(s =>
        {
            s.Summary = "Returns Chart of Account Information";
            s.Description = "Returns Chart of Accounts for the Enterprise ID and Entity ID passed.";
            s.Params["enterpriseId"] = "The Enterprise ID for the request.";
            s.Params["entityId"] = "The Entity ID to the request.";
        });
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendOkAsync("ok!");
    }
}
```

**Comment by krjaction50** [comment]
The latest beta release does NOT fix the issue.  But commenting out this code in the startup does.  This all worked in 4.4.0.

            //if (ep.Routes[0].StartsWith("/log") is false)
            //{
            //    ep.Description(b => b
            //    .Produces<ErrorResponse>(400, "application/problem+json")
            //    .Produces<ErrorResponse>(401, "application/problem+json")
            //    .Produces<ErrorResponse>(403, "application/problem+json")
            //    .Produces<ErrorResponse>(404, "application/problem+json")
            //    .Produces<ErrorResponse>(500, "application/problem+json"));

            //    ep.Summary(s =>
            //    {
            //        s[400] = PlatformRESTAPI.API.Helper.Error400Description;
            //        s[401] = PlatformRESTAPI.API.Helper.Error401Description;
            //        s[403] = PlatformRESTAPI.API.Helper.Error403Description;
            //        s[404] = PlatformRESTAPI.API.Helper.Error404Description;
            //        s[500] = PlatformRESTAPI.API.Helper.Error500Description;
            //    });
            //}

**Comment by dj-nitehawk** [comment]
yep found the issue... working on a fix...

**Comment by krjaction50** [comment]
Thanks

**Comment by dj-nitehawk** [comment]
`v5.1.0-beta8` pushed to nuget. should be available in 5 mins.

**Comment by krjaction50** [comment]
Confirmed fixed in beta 8.  Thanks
