### ISSUE TITLE
PreProcessors: NullReferenceException!

### ISSUE THREAD

**Issue by MATEUSZROGALSKI** [FastEndpoints/Library#211]
Trying to register `IPreProcessor` to `PreProcessors` of an `Endpoint` ends up with `NullReferenceException`.  
---
How to reproduce this issue in fewer steps possible:

    using FastEndpoints;
    using FluentValidation.Results;
    
    var builder = WebApplication.CreateBuilder(args);
    builder.WebHost.UseKestrel(o => o.ListenLocalhost(100));
    
    var services = builder.Services;
    services.AddFastEndpoints();
    
    var app = builder.Build();
    app.UseFastEndpoints();
    
    public sealed record class TestRequest(string value);
    public sealed record class TestResponse(string value);
    
    public sealed class TestProcessor<TRequest> : IPreProcessor<TRequest>
    {
        public async Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct) =>
            await Task.CompletedTask;
    }
    
    [HttpPost("/test")]
    public sealed class TestEndpoint : Endpoint<TestRequest, TestResponse>
    {
        public TestEndpoint()
        {
            PreProcessors(new TestProcessor<TestRequest>());
        }
    
        public override async Task HandleAsync(TestRequest request, CancellationToken ct) =>
            await SendAsync(new TestResponse(request.Value), 200, ct);
    }

![Screenshot 2022-08-31 154559](https://user-images.githubusercontent.com/77775382/187699464-04ab8a08-f6c3-4a03-90cb-7e01284211c5.png)

---
# Why this is an issue  

When we have an attributes decorating `Endpoint` we cannot override `Configure()` method in which the supposed `PreProcessors(...)` method should be placed. If there is a possibility to configure `Endpoint` with either attributes or `Configure()` method there should be a possibility to add `IPreProcessor` inside of a constructor since all that method does is just passing arguments of that method to `Definition.PreProcessorList.AddRange(...);` method or to use an attribute to add `IPreProcessors`.

**Comment by dj-nitehawk** [comment]
here's the correct way to do it:
```cs
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseKestrel(o => o.ListenLocalhost(100));
builder.Services.AddSwaggerDoc();

var services = builder.Services;
services.AddFastEndpoints();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public sealed record class TestRequest
{
    public string Value { get; init; }
};

public record class TestResponse(string value);

public sealed class TestProcessor<TRequest> : IPreProcessor<TRequest>
{
    public async Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct) =>
        await Task.CompletedTask;
}

public sealed class TestEndpoint : Endpoint<TestRequest, TestResponse>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
        PreProcessors(new TestProcessor<TestRequest>());
    }

    public override async Task HandleAsync(TestRequest request, CancellationToken ct) =>
        await SendAsync(new TestResponse(request.Value), 200, ct);
}
```

- classes/records without a parameterless ctor is not supported for request dtos.
- it has to be either attributes or `Configure()` method. using both is not supported.
- all the endpoint setup has to happen inside `Configure()` method. don't do it in ctor. the ctor is only helpful for constructor injection of dependencies if you don't like the property injection system.

**Comment by MATEUSZROGALSKI** [comment]
To clarify, I need to inject service to one particular `IPreProcessor` which can only be achieved via constructor. I tried using `Configure()` method but then `Resolve` method throws the same exception type.

**Comment by dj-nitehawk** [comment]
this is how you get stuff from ioc container in a processor.
```cs
public async Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
{
    var logger = ctx.RequestServices.GetRequiredService<ILogger<TestProcessor<TRequest>>>();
}
```
sorry looks like i've forgotten to document that.
will add to the docs soon.

**Comment by MATEUSZROGALSKI** [comment]
Thank you for the solution. NGL I felt dumb when I realized that was actually a thing 😂

**Comment by dj-nitehawk** [comment]
no worries mate. it's not obvious without the documentation. added to beta docs here: https://dev--fast-endpoints.netlify.app/docs/dependency-injection#pre-post-processor-dependencies
