### ISSUE TITLE
Global endpoint config seems to override endpoint-specific config

### ISSUE THREAD

**Issue by OrionFOTL** [FastEndpoints/Library#212]
Minimal reproducible Program.cs:

```
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc(tagIndex: 0);

var app = builder.Build();
app.UseFastEndpoints(c => c.Endpoints.Configurator = ep => ep.Description(b => b.Produces(500)));
app.UseOpenApi();
app.UseSwaggerUi3(s => s.ConfigureDefaults());
app.Run();

public class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/api/ExampleEndpoint");
        Description(b =>
        {
            b.WithTags("ExampleTag");
            b.Produces(418);
        });
    }

    public override async Task HandleAsync(CancellationToken ct)
        => await SendAsync(DateTime.Now, cancellation: ct);
}
```

Expected outcome: visiting `/swagger` should display an ExampleEndpoint under the tag "ExampleTag", which produces: response code 418 (from specific config), and response code 500 (from global config)

Actual outcome: only global config applied. Swagger displays an ExampleEndpoint under the default `default` tag, and the endpoint produces only response code 500 from the global config.

![obraz](https://user-images.githubusercontent.com/8158804/187873332-a654b838-f6f4-4aef-b597-24d5a996dbe1.png)

If you remove the global config from `.UseFastEndpoints()`, the outcome is: swagger displays the endpoint under the tag ExampleTag, which produces 418.

Tested on:
FastEndpoints.Swagger v5.0.0
FastEndpoints.Swagger v5.1.0-beta9

**Comment by dj-nitehawk** [comment]
fixed in `v5.1.0-beta12`
thanks for reporting.
