### ISSUE TITLE
ClientGen generates additional object parameter

### ISSUE THREAD

**Issue by iglak** [FastEndpoints/Library#213]
Program.cs:

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc(s => { s.DocumentName = "API"; }, shortSchemaNames: true, addJWTBearerAuth: false);
var app = builder.Build();
app.UseDefaultExceptionHandler();
app.UseFastEndpoints(c => { c.Endpoints.ShortNames = true; });
app.UseOpenApi();
app.UseSwaggerUi3(s => s.ConfigureDefaults());
app.MapCSharpClientEndpoint("/cs-client", "API");
app.Run();
```
Request.cs:
```
public class Request
{
    public string Param1 { get; set; }
}
```
Endpoint.cs:
```
public class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("/endpoint/{Param1}");
        AllowAnonymous();
    }

    public override Task HandleAsync(Request req, CancellationToken ct)
    {
        return base.HandleAsync(req, ct);
    }
}
```
Swagger:
```
"/endpoint/{Param1}": {
      "get": {
        "tags": [
          "endpoint"
        ],
        "operationId": "Endpoint",
        "parameters": [
          {
            "name": "Param1",
            "in": "path",
            "required": true,
            "schema": {
              "title": "String",
              "type": "string"
            }
          }
        ]
```

Expected outcome:
Generated client should have method with one parameter like this:
`public virtual async System.Threading.Tasks.Task<object> EndpointAsync(string param1, System.Threading.CancellationToken cancellationToken)`

Actual outcome:
Generated client has method with expected parameter but contains additional object parameter
`public virtual async System.Threading.Tasks.Task<object> EndpointAsync(object request, string param1, System.Threading.CancellationToken cancellationToken)`

Tested on:
FastEndpoints.Swagger/ClientGen 5.0.0, 5.1.0-beta9

If it's not a bug but configuration problem please provide me small example how to remove that additional parameter.

**Comment by dj-nitehawk** [comment]
i believe this was fixed in beta10
give `v5.1.0-beta12` a try and let me know if the problem still persists.

**Comment by iglak** [comment]
Confirmed. In `v5.1.0-beta12` client generates correctly.
