### ISSUE TITLE
Exception Middleware not being called

### ISSUE THREAD

**Issue by disagol** [FastEndpoints/Library#215]
On errors the exception middleware defined is not being called.

Config via app.UseMiddleware<ExceptionHandlingMiddleware>().

HandleExceptionAsync is not being called after exception thrown from Endpoint and validation enabled.

**Comment by dj-nitehawk** [comment]
does #186 help?

**Comment by dj-nitehawk** [comment]
updated beta docs: https://dev--fast-endpoints.netlify.app/docs/exception-handler.#disable-validation-error-catching
