### ISSUE TITLE
Problem Details with SendNotFoundAsync?

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/Library#222]
SendNotFoundAsync does not appear to support using problem details, is that intentional? It would be great to be able to use problem details model for all the SendXXXXAsync 4XX exceptions.

**Comment by dj-nitehawk** [comment]
it is like that on purpose but you can override that behavior. here's an example: 
```cs
app.UseFastEndpoints(c =>
{
    c.Errors.ResponseBuilder = (failures, statusCode) =>
    {
        if (statusCode == 404)
        {
            return new ProblemDetails()
            {
                Title = "Not found!",
                Status = statusCode,
            };
        }
        else
        {
            var errors = failures.GroupBy(f => f.PropertyName).ToArray();
            return new ValidationProblemDetails(
                errors.ToDictionary(
                    keySelector: e => e.Key,
                    elementSelector: e => e.Select(m => m.ErrorMessage).ToArray()))
            {
                Title = "One or more validation errors occurred.",
                Status = statusCode
            };
        }
    };
});
```

**Comment by altmank** [comment]
Hey, I tried to implement this and it simply didn't work. This response builder is not triggered when using something like SendNotFoundAsync. Was there some other piece here that wasn't mentioned?

It would be awesome if ProblemDetails had the option to be treated like a first class citizen in this library, if given the option between a custom implementation or a standard one for Problem details I'd prefer to use the more common standard implementation. Was there some specific goal in mind with going for custom data models instead of problem details in this library?

**Comment by dj-nitehawk** [comment]
you're gonna need a custom extension method for the `not found` to go through the `error response builder function`.
here's a working example: 
```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints(c =>
{
    c.Errors.ResponseBuilder = (failures, ctx, statusCode) =>
    {
        if (statusCode == 404)
        {
            return new ProblemDetails()
            {
                Title = "Not found!",
                Status = statusCode,
            };
        }
        else
        {
            var errors = failures.GroupBy(f => f.PropertyName).ToArray();
            return new ValidationProblemDetails(
                errors.ToDictionary(
                    keySelector: e => e.Key,
                    elementSelector: e => e.Select(m => m.ErrorMessage).ToArray()))
            {
                Title = "One or more validation errors occurred.",
                Status = statusCode
            };
        }
    };
});

app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public class Request
{
    public int Mode { get; set; }
}

public class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("test/{Mode}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        switch (r.Mode)
        {
            case 404:
                await this.NotFoundAsync();
                break;

            case 400:
                AddError(r => r.Mode, "This is a validation error!");
                await SendErrorsAsync();
                break;

            default:
                await SendOkAsync("all good...");
                break;
        }
    }
}

public static class EndpointExtensions
{
    public static Task NotFoundAsync(this IEndpoint ep)
        => ep.HttpContext.Response.SendErrorsAsync(new List<ValidationFailure>() { new() }, 404);
}
```
there's two reasons why `ProblemDetails` is not a first class citizen.

1. it's a class from MVC and i didn't wanna touch anything MVC related.
2. i have a long standing belief that 400 error responses and 500 error responses should look drastically different. so we have two different classes of our own for that. `ErrorResponse` for 400 errors. and `InternalErrorResponse` for 500 errors. if someone doesn't wanna use the defaults, they can easily switch to `ProblemDetails` via the `error response builder function`.

the requirement to be able to send a json body with error details for a 404 response had never come up until now :-)

**Comment by altmank** [comment]
Thank you, I appreciate you sharing your thoughts and some code samples.

**Comment by altmank** [comment]
Regarding your comment about 404, 404 was just an example, it could be say any 4XX code. Basically if I'm returning any 4XX error, I want to be returning a problem details. I also want to be able to pass details that may be needed to populate the problem details object. So having to go through the intermediate SendErrorsAsync and pass the details using ValidationFailure object is kind of clunky right now and requires a lot of custom wiring. Is there some middle ground here potentially that could make this use case more seamless?

I understand the desire to not tie to an MVC class, but the problem details model can be implemented directly if that is the only concern and its a separate specification. You are also using the same media type as defined in the spec in your custom validation error handling, but then not implementing the spec. That may be a source of confusion for consumers who see "application/problem+json" and expect to have a data model that aligns with that RFC7807 specification.

**Comment by dj-nitehawk** [comment]
unfortunately `ProblemDetails` model cannot be used at this stage as it would break hundreds of existing client applications.
so i highly doubt this can ever be done, unless we change the library in a major way that will break backwards compatibility, in which case the switch to `ProblemDetails` would be one of the breaking changes.

so i'm afraid there's no easy/elegant solution to the issue at hand.

you'd have to either use an extension method like above or make your own base endpoint class something like this:
```cs
public class EndpointBase<TRequest, TResponse> : Endpoint<TRequest, TResponse> where TRequest : notnull, new()
{
    public Task SendProblemAsync(ProblemDetails problem, int statusCode = 400)
    {
        HttpContext.Items["problem"] = problem; //access the object later in the error response builder
        return SendErrorsAsync(statusCode);
    }
}
```
