### ISSUE TITLE
Global settings and endpoints settings.

### ISSUE THREAD

**Issue by MistyKuu** [FastEndpoints/Library#223]
First of all - great library, keep it up! 
I think it's pretty common scenario but I don't know how to configure it. I'd expect that whatever I configure in global configurator will be common for all endpoints + I'll have the ability to extend it. E.g. I have a few common status codes which I want to attach to response of every endpoint + I want to add them in the endpoint itself. For example all my endpoints can produce 500 and 401 but in addition EndpointA would also produce 409. I have no idea how to do it with global settings. My try:

```
 app.UseFastEndpoints(c =>
    {
        c.Endpoints.Configurator = ep =>
        {
            ep.Description(b =>
                b.ProducesProblem(StatusCodes.Status500InternalServerError) .ProducesProblem(StatusCodes.Status401Unauthorized)
                );
        };
    });
```

```
public class EndpointA: Endpoint<Req>
{
    public override void Configure()
    {
        Post(xx);
        Description(b => b.Produces(StatusCodes.Status409Conflict));
    }
}
```

Current result: 500,401. Expected result: 500,401,409.
Edit: It is also messing up with Options e.g if I set:
`Options(x => x.WithTags(RouteGroups.Snapshots))`
 in the endpoint it is getting ignored.

**Comment by dj-nitehawk** [comment]
pls upgrade to `v5.1` as this didn't work correctly in v5.0 and do the following:
```cs
app.UseFastEndpoints(c => c.Endpoints.Configurator = ep =>
{
    ep.Description(b => b
    .Produces<ErrorResponse>(400, "application/problem+json")
    .Produces(401)
    .Produces<InternalErrorResponse>(500, "application/problem+json"));

    ep.Summary(s =>
    {
        s[401] = "Unauthorized response.";
        s[400] = "Validation error response.";
        s[500] = "Internal server error response.";
    });
});
```

```cs
public override void Configure()
{
    Get("/test");
    AllowAnonymous();
    Description(b => b.Produces(409));
    Summary(s => s[409] = "Resource conflict response.");
}
```

do note that instead of `ProblemDetails` model, FE uses `ErrorResponse` dto for `4XX` errors and `InternalErrorResponse` for `500` errors by default. you can however override that as shown in #222 if you prefer.

**Comment by MistyKuu** [comment]
Thx!
