### ISSUE TITLE
OpenApiIgnoreAttribute does not hide model property from swagger request schema

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/Library#226]
I'm trying to hide a field in the request model that gets bound from the route so that it also doesn't show up in the request body in the Swagger example. 

However it appears to have no effect, is this something that FastEndpoints has to add support for?

![image](https://user-images.githubusercontent.com/22986384/189214518-8a978337-3bfe-42f9-a091-b6ee71f4b0b7.png)

**Comment by dj-nitehawk** [comment]
this does work as intended:
```cs
public record Request
{
    [BindFrom("guid-id")]
    public Guid GuidId { get; init; }

    public int IntId { get; init; }
}

public class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Post("test/{guid-id}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendOkAsync();
    }
}
```
i believe you just have a mismatched property name & route param, in which case you just need to use the `BindFrom` attribute: https://fast-endpoints.com/docs/model-binding#mismatched-property-names-2

![screen-record-1662679140](https://user-images.githubusercontent.com/7043768/189242187-3781435a-22c5-404d-b533-b7c3679510f7.png)

**Comment by altmank** [comment]
Ahhh, thank you. I actually didn't realize the BindFrom attribute also had the effect of hiding from the swagger model as well.


I wrote a custom schema processor and then later added BindFrom for binding purposes but it looks like that workaround was unnecessary.

**Comment by dj-nitehawk** [comment]
you're most welcome...
also received the donation. much appreciated 🙏
