### ISSUE TITLE
Add Throttle rate limiting as attribute?

### ISSUE THREAD

**Issue by MarcusOtter** [FastEndpoints/Library#227]
Hello, thank you for this wonderful library.

I was wondering if the [`Throttle()`](https://fast-endpoints.com/docs/rate-limiting#endpoint-rate-limiting) method used in `Configure()` could ever be added as an attribute?
From the [docs](https://fast-endpoints.com/docs/get-started#configuring-using-attributes):
> Instead of overriding the Configure() method, endpoint classes can be annotated with the following attributes:
>
>    [Http{VERB}]
>    [AllowAnonymous]
>    [Authorize]
>
> **Advanced usage however does require overriding Configure().**

I'm assuming in this case, rate limiting is advanced usage. I thought I'd ask anyways if there's any chance of supporting this as an attribute in the future as I prefer attributes. Adding this would mean that my endpoints can be consistent with using attributes over the configure method.

Thanks, and consider enabling GitHub Sponsors here on GitHub :)

**Comment by dj-nitehawk** [comment]
added in `v5.1.1-beta3`

about gh sponsors, i've tried to set that up but couldn't as i don't have a bank account in a country that is supported by stripe unfortunately.

there is however a paypal donation link in the sponsor button above ;-)
