### ISSUE TITLE
Case sensitivity for Swagger Authentication Scheme

### ISSUE THREAD

**Issue by OFark** [FastEndpoints/Library#229]
It's a really small change, but the scheme for JWT Authentication is "bearer" not "Bearer" and yes Postman cares. Don;t know why but it does.

if you could just change 
```cs
public static void EnableJWTBearerAuth(this AspNetCoreOpenApiDocumentGeneratorSettings settings)
    {
        settings.AddAuth("JWTBearerAuth", new OpenApiSecurityScheme
        {
            Type = OpenApiSecuritySchemeType.Http,
            Scheme = "Bearer",
            BearerFormat = "JWT",
            Description = "Enter a JWT token to authorize the requests..."
        });
    }
```
to
```cs
public static void EnableJWTBearerAuth(this AspNetCoreOpenApiDocumentGeneratorSettings settings)
    {
        settings.AddAuth("JWTBearerAuth", new OpenApiSecurityScheme
        {
            Type = OpenApiSecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            Description = "Enter a JWT token to authorize the requests..."
        });
    }
```

Would be much appreciated.

![image](https://user-images.githubusercontent.com/4558132/189361360-3c326b70-8e80-4a65-b307-78a5c3e67624.png)

**Comment by dj-nitehawk** [comment]
done ;-)
`v5.1.1-beta4` has been pushed out

**Comment by dj-nitehawk** [comment]
@OFark looks like the correct scheme name according to the RFC is `Bearer`
https://www.rfc-editor.org/rfc/rfc7235#section-5.1
https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
https://source.dot.net/#Microsoft.AspNetCore.Authentication.JwtBearer/JwtBearerDefaults.cs,14

maybe postman is making a mistake?

**Comment by OFark** [comment]
I'd be inclined to agree, but they're hardly a small outfit. Must know what they're doing right?

**Comment by dj-nitehawk** [comment]
i guess postman is going by swagger documentation: https://swagger.io/docs/specification/authentication/bearer-authentication/
according to which `bearer` is the correct value.

**Comment by OFark** [comment]
Bug reported to Postman, Authentication tokens should be case-insensitive. https://www.rfc-editor.org/rfc/rfc7235#section-2.1 
My apologies, you would have thought Postman, being as popular as they are, wouldn't be doing this.

**Comment by dj-nitehawk** [comment]
okie then... let's switch it back to `Bearer` then?

**Comment by OFark** [comment]
Yeah, I mean I don't think it should matter, but in most places, it does seem to be "Bearer".

**Comment by OFark** [comment]
Postman have raised my case as a Bug! How am I the first person to raise this??? 🙄

**Comment by dj-nitehawk** [comment]
guess it's so insignificant that it flew under everyone's radar ;-)
