### ISSUE TITLE
FastEndpoints tries to send default Error Response right after I have sent custom Error Response.

### ISSUE THREAD

**Issue by TopSwagCode** [FastEndpoints/Library#230]
Hi. I have a problem where a exception is thrown after my PreProcessor sends errors response to consumer. documentation. https://fast-endpoints.com/docs/pre-post-processors#short-circuiting-execution

So I built my own SendErrors, because I have to follow a specific standard that my company has for all ErrorMessages. This SendErrors is used both in My ExceptionHandler and in my PreProcessors.

In both cases it works and the right error message is shown. But in PreProcessors there is also coming a exception from FastEndpoints framework after my response has been written to the consumer.

Exception:

> System.InvalidOperationException: StatusCode cannot be set because the response has already started.
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
>          at FastEndpoints.HttpResponseExtensions.SendErrorsAsync(HttpResponse rsp, List`1 failures, Int32 statusCode, JsonSerializerContext jsonSerializerContext, CancellationToken cancellatio
> n)
>          at FastEndpoints.Endpoint`2.SendErrorsAsync(Int32 statusCode, CancellationToken cancellation)
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
> 

SendErrors:

```
    public static async Task SendErrors(this HttpContext httpContext, int statusCode, string message, IEnumerable<SubError> subErrors)
    {
        httpContext.Response.ContentType = "application/json";
        httpContext.Response.StatusCode = statusCode;

        var result = new GenericErrorResult
        {
            Method = httpContext.Request.Method,
            RequestUri = httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget!,
            Status = statusCode.ToString(),
            SubErrors = subErrors,
            Timestamp = DateTime.UtcNow.ToString("dd-MM-yyyy hh:mm:ss"),
            Message = message,
        };

        await httpContext.Response.WriteAsJsonAsync(result);
    }

```

PreProcessor:

```
public class ValidationPreProcessor : IGlobalPreProcessor
{
    public Task PreProcessAsync(object req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
    {
        if (failures.Count > 0)
        {
            var subErrors = failures.Select(f => new SubError {Field = f.PropertyName, RejectedValue = f.AttemptedValue?.ToString() ?? string.Empty,Message = f.ErrorMessage});
            
            return ctx.SendErrors((int)HttpStatusCode.BadRequest, "Error occured during validation", subErrors);
        }

        return Task.CompletedTask;
    }
}
```

**Comment by TopSwagCode** [comment]
So I just reproduced the error in your example web project.

Steps:

* Have validators fail
* Have preprocessor send response
* Exception will be made because it tries to send validation errors after already sent.

**Comment by TopSwagCode** [comment]
Entire stacktrace in FastEndpoints: 
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.InvalidOperationException: StatusCode cannot be set because the response has already started.
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ThrowResponseAlreadyStartedException(String name)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
>          at FastEndpoints.HttpResponseExtensions.SendErrorsAsync(HttpResponse rsp, List`1 failures, Int32 statusCode, JsonSerializerContext jsonSerializerContext, CancellationToken cancel
> lation) in C:\Users\JRY037\git\Library\Src\Library\Extensions\HttpResponseExtensions.cs:line 129
>          at FastEndpoints.Endpoint`2.SendErrorsAsync(Int32 statusCode, CancellationToken cancellation) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.Send.cs:line 110
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 88
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 95
>          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthori
> zationResult authorizeResult)
>          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
> warn: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[2]
>       The response has already started, the error handler will not be executed.
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
>       An unhandled exception has occurred while executing the request.
>       System.InvalidOperationException: StatusCode cannot be set because the response has already started.
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ThrowResponseAlreadyStartedException(String name)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
>          at FastEndpoints.HttpResponseExtensions.SendErrorsAsync(HttpResponse rsp, List`1 failures, Int32 statusCode, JsonSerializerContext jsonSerializerContext, CancellationToken cancel
> lation) in C:\Users\JRY037\git\Library\Src\Library\Extensions\HttpResponseExtensions.cs:line 129
>          at FastEndpoints.Endpoint`2.SendErrorsAsync(Int32 statusCode, CancellationToken cancellation) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.Send.cs:line 110
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 88
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 95
>          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthori
> zationResult authorizeResult)
>          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
>          at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
>       The response has already started, the error page middleware will not be executed.
> fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
>       Connection ID "18302628904424177682", Request ID "80000013-0004-fe00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
>       System.InvalidOperationException: StatusCode cannot be set because the response has already started.
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ThrowResponseAlreadyStartedException(String name)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
>          at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
>          at FastEndpoints.HttpResponseExtensions.SendErrorsAsync(HttpResponse rsp, List`1 failures, Int32 statusCode, JsonSerializerContext jsonSerializerContext, CancellationToken cancel
> lation) in C:\Users\JRY037\git\Library\Src\Library\Extensions\HttpResponseExtensions.cs:line 129
>          at FastEndpoints.Endpoint`2.SendErrorsAsync(Int32 statusCode, CancellationToken cancellation) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.Send.cs:line 110
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 88
>          at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct) in C:\Users\JRY037\git\Library\Src\Library\Endpoint\Endpoint.cs:line 95
>          at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthori
> zationResult authorizeResult)
>          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
>          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
>          at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
>          at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished HTTP/2 PUT https://localhost:44318/api/customer/update-with-header application/json 45 - 403 - - 4950.0640ms
>

**Comment by TopSwagCode** [comment]
So after digging around I found, that if I changed the implementation of SendErrorsAsync, to check if Response is already in process and do anything if it is. Like so:

Src/Library/Extensions/HttpResponseExtensions.cs

```
    /// <summary>
    /// send a 400 bad request with error details of the current validation failures
    /// </summary>
    /// <param name="statusCode">the status code for the error response</param>
    /// <param name="cancellation">optional cancellation token. if not specified, the <c>HttpContext.RequestAborted</c> token is used</param>
    protected Task SendErrorsAsync(int statusCode = 400, CancellationToken cancellation = default)
    {
        if(HttpContext.Response.HasStarted)
            return Task.CompletedTask;
        
        return HttpContext.Response.SendErrorsAsync(ValidationFailures, statusCode, Definition.SerializerContext, cancellation);
    }
```

I don't know if this HasStarted check should be on all methods. So if pipeline tries to send response that it doesn't try to do it again.

**Comment by TopSwagCode** [comment]
Just a bonus info. I know there is this:

```
app.UseFastEndpoints(c =>
{
    c.Errors.ResponseBuilder = (failures, status) =>
    {
        var list = new List<KeyValuePair<string, string>>();
        foreach (var err in failures)
        {
            list.Add(new(err.PropertyName, err.ErrorMessage));
        }
        return list;
    };
});
```

But we need in our errors to be a specific format and they need to include:

            Method = httpContext.Request.Method,
            RequestUri = httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget!,

**Comment by TopSwagCode** [comment]
Okay. So just digged deeper again. I can see in file: Src/Library/Endpoint/Endpoint.cs

```
            await RunPreprocessors(Definition.PreProcessorList, req, HttpContext, ValidationFailures, ct);

            if (ResponseStarted) //HttpContext.Response.HasStarted doesn't work in AWS lambda!!!
                return; //response already sent to client (most likely from a preprocessor)
```

So looks like it already should stop if response have started. But it doesn't.
But it worked for me when I added the same logic in the HttpResponseExtensions.cs mentioned 2 comments ago.

**Comment by dj-nitehawk** [comment]
i've changed the signature of the global error response builder to include the `HttpContext`.
i believe that should solve it right?

**Comment by TopSwagCode** [comment]
https://github.com/FastEndpoints/Library/pull/231

Created this pullrequest showing the error :D

**Comment by TopSwagCode** [comment]
> i've changed the signature of the global error response builder to include the `HttpContext`. i believe that should enable you to use the error response builder instead of a pre-processor for this right?

I will try updating and see if that fixes my problem later :) But try looking at my Pullrequest showing the issue. Others might try the same sending response from Pipeline when there is validation errors.

**Comment by dj-nitehawk** [comment]
with `v5.2.0-beta2` you can update your extension method like below, and that should do the trick.
also anywhere the response is being sent should not fail silently imho. an exception definitely should be thrown just so the developer knows that something wrong is being done.
```cs
public static class Extensions
{
    public static async Task SendErrors(this HttpContext httpContext, int statusCode, string message, IEnumerable<SubError> subErrors)
    {
        if (httpContext.ResponseStarted()) //add this here
            throw new InvalidOperationException("something else has sent the response already!");

        httpContext.MarkResponseStart(); //add this here - this will prevent the endpoint handler from executing after pre-processors are done.

        httpContext.Response.ContentType = "application/json";
        httpContext.Response.StatusCode = statusCode;

        var result = new GenericErrorResult
        {
            Method = httpContext.Request.Method,
            RequestUri = httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget!,
            Status = statusCode.ToString(),
            SubErrors = subErrors,
            Timestamp = DateTime.UtcNow.ToString("dd-MM-yyyy hh:mm:ss"),
            Message = message,
        };

        await httpContext.Response.WriteAsJsonAsync(result);
    }
}
```

**Comment by TopSwagCode** [comment]
I totally understand what I need to do. Just sharing there is still a chance for others to run into similar issue. 

The same issue will happen if you have some pipeline that returns forbidden and there also is validations errors

**Comment by dj-nitehawk** [comment]
will update the documentation about the need to mark response start anytime you're manually writing to the response.
thanks for bringing this to my attention.
