### ISSUE TITLE
question: Equivalent of StatusCode method

### ISSUE THREAD

**Issue by andreas-soroko** [FastEndpoints/Library#234]
Hello,

is there a `StatusCode` method Equivalent? (`return StatusCode(StatusCodes.Status304NotModified)`) 
Just want to return in some cases the status `304`. 
Currently i am doing it with

```
HttpContext.Response.HttpContext.Items[0] = null;
HttpContext.Response.StatusCode = StatusCodes.Status304NotModified;
```

based on [HttpResponseExtensions](https://github.com/FastEndpoints/Library/blob/f47b01732de472b0162efb8407dca48a4c52b421/Src/Library/Extensions/HttpResponseExtensions.cs#L142)

**Comment by dj-nitehawk** [comment]
you could write an extension method like this:
```cs
public static class EndpointExtensions
{
    public static Task SendStatusCode(this IEndpoint ep, int statusCode, CancellationToken ct = default)
    {
        ep.HttpContext.MarkResponseStart();
        ep.HttpContext.Response.StatusCode = statusCode;
        return ep.HttpContext.Response.StartAsync(ct);
    }
}
```
and use it like this:
```cs
public override async Task HandleAsync(Request r, CancellationToken ct)
{
    await this.SendStatusCode(403);
}
```
