### ISSUE TITLE
Swagger XML Comments

### ISSUE THREAD

**Issue by shawndewet** [FastEndpoints/Library#237]
In the Response Model, I have the XML Comments defined like so:
![image](https://user-images.githubusercontent.com/1556343/190302372-233881b1-f77e-464f-b650-89d26ab6cb38.png)

But I see they don't appear on the XML Schema definition.  Is there something I should be doing differently to get this to work?

I have another API that is just straight Swagger over ASP.Net Core Controllers written a few years ago, and there the Swagger docs generate the XML Comments, like so (note it even detects the field-validations):
![image](https://user-images.githubusercontent.com/1556343/190302835-0cd8af2b-76e3-437f-b9fc-424537b2c511.png)

**Comment by dj-nitehawk** [comment]
it works:

![image](https://user-images.githubusercontent.com/7043768/190306860-bec80672-6446-4855-a351-2384f0cebc7c.png)

sample code:
```cs
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

public class Request
{
    /// <summary>
    /// this is the description of the age field
    /// </summary>
    public int Age { get; set; }
}

public class Response
{
    /// <summary>
    /// this is the description for the message field
    /// </summary>
    public string Message { get; set; }
}

public class Endpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendOkAsync();
    }
}
```

make sure you've enabled generating the xml documentation file in your csproj:
https://fast-endpoints.com/docs/swagger-support#enabling-xml-documentation

**Comment by shawndewet** [comment]
uhg I feel like an idiot...I just blanked over that looking through the documentation.  Thanks @dj-nitehawk .
