### ISSUE TITLE
Endpoint type documentation missing mention of EndpointWithMapper<TRequest, TMapper>

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/Library#240]
https://fast-endpoints.com/docs/get-started#endpoint-types does not mention EndpointWithMapper<TRequest, TMapper> as a valid option that can be inherited from on an endpoint.

It does seem to get mentioned later in the last section of https://fast-endpoints.com/docs/domain-entity-mapping#mapping-logic-in-a-separate-class that exists and how to use it with the mapper.

Requesting that https://fast-endpoints.com/docs/get-started#endpoint-types be updated to list this missing option for clarity.

**Comment by dj-nitehawk** [comment]
that is actually done on purpose. didn't wanna overwhelm beginners on the first page. and it's not really needed until you actually get to the point of using mappers. also IDE intellisense should show all variants in one place when you type in `Endpoint...` which the user can cycle through to see what they wanna use.
