### ISSUE TITLE
It is recommended that beta version iterations use two digits to avoid Nuget error prompting upgrades

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#241]
![image](https://user-images.githubusercontent.com/13956765/190895992-c9f3017e-c07b-4ed1-a8d8-83353525b14e.png)

It is recommended that beta version iterations use two digits to avoid Nuget error prompting upgrades, eg. v1 -> v01 :)

**Comment by dj-nitehawk** [comment]
great... will do!
