### ISSUE TITLE
Whether the version parameter of FastEndpoints.Swagger.DocumentProcessor can provide scope support 

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/Library#242]
```
     //Here minEndpointVersion support !?
    services.AddSwaggerDoc(maxEndpointVersion: 0, settings: s =>
      {
      } );
```

```
    public DocumentProcessor(int maxEndpointVersion)
    {
        maxEpVer = maxEndpointVersion;
    }
```

Whether the version parameter of FastEndpoints.Swagger.DocumentProcessor can provide scope support, for example sometimes I need to limit the version of a document to between 2-3, but currently only maxEndpointVersion can be configured

**Comment by vipwan** [comment]
This only involves a few lines of code in the [FastEndpoints.Swagger] and won't have any other effects, maybe I could commit a PR

**Comment by dj-nitehawk** [comment]
sure go ahead and send a PR
thanks!

**Comment by dj-nitehawk** [comment]
but make sure to test things well and make sure that existing code won't break.
specially since we don't have any tests for the swagger stuff.

**Comment by vipwan** [comment]
Yes, that's the premise !

**Comment by vipwan** [comment]
#244
